### ISSUE TITLE
SyntaxError: Named export 'importClass' not found.

### ISSUE THREAD

**Issue by AddictArts** [MarkusJx/node-java-bridge#106]
**Describe the bug**
The hello world example does not work out of the box.

**To Reproduce**
Try the hello world example.

**Expected behavior**
No import errors

**Environment**

- Windows 11 64bit
- Node 20 LTS
- Java 1.8

**Additional context**

Needed to use

```
import pkg from "java-bridge";
const { importClass } = pkg;
```

Then I also had to use the libPath option for the jvm, but that was not an issue.

**Comment by MarkusJx** [comment]
Are you using Typescript or an ESM module? The example in the readme is written in Typescript and runs fine if compiled to CommonJS. But I've never tested ESM, so this may be an issue.

**Comment by AddictArts** [comment]
Hi yes, I am using ESM and not transpiling using vite  / webpack / babel / other ... 

It makes sense it could work if transpiled, I guess that was implied, but the above works if anyone is using `type: "module"`.
