### ISSUE TITLE
Java setPropery and getProperty don't work for own names

### ISSUE THREAD

**Issue by tripower** [MarkusJx/node-java-bridge#50]
it works for "normal" properties like "java.version"
  but with a self named one it brings an error and stops running
  or getProperty delivers a value which has never been set!!!
    
  // example
  const System = importClass('java.lang.System');
  System.out.printlnSync('show: ' + System.getPropertySync('java.version')); // => OK
  System.setPropertySync('testflag', 'xxx'); // => NOK
  System.out.printlnSync('show: ' + System.getPropertySync('testflag')); // => NOK
  System.out.printlnSync('done');

**Comment by MarkusJx** [comment]
Should be fixed in version `2.2.1-beta.1`, the binaries should be available in ~10 Minutes

**Comment by tripower** [comment]
oh
quick fix
thx

**Comment by MarkusJx** [comment]
Is this fixed, can we close this issue?

**Comment by tripower** [comment]
you can close it 
thx
do work!
