### ISSUE TITLE
Electron ASAR package

### ISSUE THREAD

**Issue by tripower** [MarkusJx/node-java-bridge#52]
Hello

Bridge do not work 
no matter if node modules (java-bridge, java-bridge-win32-ia32-msvc)
in the ASAR or not 

![java bridge ASAR unpacked](https://user-images.githubusercontent.com/25051422/205693376-30568865-2ebe-4fc4-8b54-25303751adba.jpg)

**Comment by MarkusJx** [comment]
Will be fixed in the latest beta build `2.2.1-beta.3`. I've added a new flag to `ensureJvm`: [`isPackagedElectron`](https://github.com/MarkusJx/node-java-bridge#notes-on-electron).

Just set that to `true` and everything should work as expected™

**Comment by MarkusJx** [comment]
Binaries will be available in ~10 Minutes

**Comment by tripower** [comment]
thx 🤗

**Comment by tripower** [comment]
works with 2.2.1beta5
thanks 🤗
