### ISSUE TITLE
SAX parser - premature end

### ISSUE THREAD

**Issue by skvlakov** [MarkusJx/node-java-bridge#6]
Hello,
I don't know if the issue is with your bridge "node -> java" or with me.
But the attached example "test1.zip" below (with a few modifications) is working with "joeferner / java" bridge.

Problem is with the "proxy" call (interface->implementation) ??
In the example I have "SAX handler implementation" handling "SAX events":

startDocument, startElement, ...

and in the "resources" directory is "xml file".

I am admitting I am a pig, anyway I will attach some source files with the "Javascript" and some "java". It is very short:
[test1.zip](https://github.com/MarkusJx/node-java-bridge/files/8929037/test1.zip)

The 2 java files in "java-src" dir must be compiled.
There is "java classpath" set in the script.

I run it like this:
> node scripts\test5-sync-markusjx-java.js

And the problem is the example ends prematurely - it is reporting / printing 2 XML nodes therefore it somehow will assemble the "node - java" bridge successfully but it should print around 30-40 XML nodes. As mentioned above with "joeferner / java" bridge it is working OK.
Thanks for your effort.

**Comment by MarkusJx** [comment]
Yeah, this is my fault, I'll take care of it. But this may take a while

**Comment by skvlakov** [comment]
Thank you, you are awsome.

Maybe I would like to mention that before `npm i @markusjx/java` it was useful to set `JAVA_HOME` to refer to the place where `jvm.dll` will be found.
E.g. I normally use:
`set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172`
but the compilation **CRASHED** because the compilation could not find `jvm.dll`.
I had to set:
`set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172\jre`
for the compilation to be successful. It found:
`C:\Program Files\Java\jdk1.8.0_172\jre\bin\server\jvm.dll`
But maybe in the future `java 1.8` will not be used so often and the higher versions of Java like "Zulu" will not have these problems finding `jvm.dll`.

**Comment by MarkusJx** [comment]
Huh, I did not know that. I'm using ``find-java-home`` to find the jdk but possibly my search strategy is garbage. I'll look into that at some point, thank you for the heads up :) Anyways, I found the cause for the crash, but found another one right around the corner, I'll start working on that tomorrow

**Comment by MarkusJx** [comment]
So I fixed some of the issues, the program doesn't crash anymore, if an error occurs and the arrays are now converted correctly, but it won't exit after an exception has been thrown inside a proxy. I'll get back to these issues once I've got more time. Anyways, you can try out the changes using this command:
```sh
npm i MarkusJx/node-java-bridge#fix/arrayConversion
```

**Comment by MarkusJx** [comment]
I did some more changes, and this package should now fully work with your script. It may take a while for the program to exit, as the garbage collector has to destroy all proxy instances before the program can exit. Let me know if the changes are working or if you encountered any more issues

**Comment by skvlakov** [comment]
Hello,
I tried it. Thank you. It really is much better.
I modified a little the code:

[test2.js.zip](https://github.com/MarkusJx/node-java-bridge/files/8940475/test2.js.zip)

On the "development machine / host" where I run `npm i MarkusJx/node-java-bridge#fix/arrayConversion` It will correctly print all the "attribute and element nodes".

### 1.---
Please, how is it with the deployment in the production ?

I tried (as a quick test) to copy all the files 1:1 from the "development machine" to the "production machine". I simulate the "production environment" where e.g. internet connection is strictly forbidden (so, no `npm install ...` is allowed) and I just did a plain copy to the "production machine".
Both hosts / machines (development and production) have the same version of node.js, both computers are "Intel x64 i7". A little bit different models but overall the underline architecture is almost the same and nevertheless on the "production machine" I get the error / exception shown below:

>node scripts\test5-sync-markusjx-java.js
```diff
- ...\node_modules\@markusjx\java\index.js:42
-         java = new native.java(jvmPath, version);
-                ^

- Error: Could not load the library. Reason: The specified module could not be found.
-     at ensureJVM (...\node_modules\←[4m@markusjx←[24m\java\index.js:42:16)
-     at Object.append (...\node_modules\←[4m@markusjx←[24m\java\index.js:64:13)
-     at Object.<anonymous> (...\scripts\test5-sync-markusjx-java.js:10:16)
- ←[90m    at Module._compile (node:internal/modules/cjs/loader:1105:14)←[39m
- ←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)←[39m
- ←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
- ←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
- ←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
- ←[90m    at node:internal/main/run_main_module:17:47←[39m
```

### 2.---
Problem with "**Sync**" version of the `parse()` function:
`saxParser.parseSync()`
`xmlReader.parseSync()`
The `parseSync()` calls will get stuck.

### 3.---
And I also noticed it is rather slower than the **joeferner/java** - which is maybe because everything is "asynchronous" with a lot of `await` statements.
In **joeferner/java** I can disable "async" behavior completely with one option:
```Javascript
java.asyncOptions = {
   asyncSuffix: undefined,     // Don't generate node-style methods taking callbacks / Promises
   syncSuffix: "",              // Sync methods use the base name
}

**Comment by MarkusJx** [comment]
Hi,

I've pushed some commits, those may fix some issues, here are my thoughts on your problems:
1. To avoid setting ``jvmLibPath.json``, you can pass a path to ``java.createJVM()``. Additionally, this package is capable of finding the JVM instance at runtime (the .dlls are not linked with the native binary):
```ts
const java = import('@markusjx/java');

const libraryPath = await java.findJVM();
java.createJVM(libraryPath);
```
2. Yes, ``parseSync`` will get stuck. And there is no way to avoid this, since node.js is single-threaded, so calling ``parseSync`` will cause the java implementation to be called, which itself will call the proxy instance you've created using ``newProxy(...)``. But here's the problem: This package will try to call the javascript methods you've defined in your proxy instance, but the (and this is the only thread) thread where those methods may run is already occupied waiting for the result of ``parseSync``. This took me a while to figure out, but this is how it's going down. The reason why the async version does work is because the waiting for the result of ``parse`` is done in a new thread, so this doesn't occupy the javascript thread, allowing the proxy methods to run.
```
parseSync -- calls --> Java proxy -- calls --> your js (proxy) method
     ^                                              |
     |                                              |
     -------------------- waits for -----------------
```
4. Well, you can't disable the async stuff with this package, you just don't have to use those methods :)
5. Maybe this is fixed with the stuff I pushed, I don't know, I was not able to re-produce this issue.

**Comment by skvlakov** [comment]
Thank you.
