### ISSUE TITLE
`GLIBC_2.33` not found

### ISSUE THREAD

**Issue by KangJuO** [MarkusJx/node-java-bridge#72]
**Describe the bug**
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found

appear right after start project

**Environment**
-   OS: debian 11 , amd64
-   Node.js version: [18]
-   Java version: [11]
-   Version of this package: [2.2.3]

i guess debian Linux 11 still use GLIBC_2.31 
should i use downgraded version of java-bridge?
if right which version supports debian 11?

**Comment by MarkusJx** [comment]
Which debian version are you using exactly? Debian 11 (or "bullseye") is the latest version of debian and *should* work, although I'm not quite sure about this, but bullseye should use the same version of GLIBC as ubuntu 22, if I recall correctly.

**Comment by KangJuO** [comment]
@MarkusJx 
Debian 11 is correct
```
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
```
also
```
ldd (Debian GLIBC 2.31-13+deb11u5) 2.31
```

i tried re-build container several times but still same

**Comment by KangJuO** [comment]
@MarkusJx 
Thx it works to me :)
