### ISSUE TITLE
no error message occurs if wrong MS Visual C++ Redist. is installed

### ISSUE THREAD

**Issue by tripower** [MarkusJx/node-java-bridge#75]
I have had the problem
that after the require of the bridge
```
console.log("info 1");
const {importClass} = require('java-bridge');
console.log("info 2");
const  java = require('java-bridge');
console.log("info 3");
```
nothing else happened
my app starts but the beidge was not working
no info, error...
only the Output
**info 1**

I only saw that an old MS Visual C++ Redist. (Version 2012)  was installed

for try and error
I installed MS Visual  C++ 2015 Red. x86
and than it was working

so would it be possible to write
console log or other infos
If in the background of the bridge
something goes wrong?

**Comment by tripower** [comment]
ok
Pity
hoped that another try catch or check in your backend
could detect it
maybe you have an idea
but thanks for doc 🤗

**Comment by MarkusJx** [comment]
I've tried to reproduce this issue on a windows 10 x64 (I wasn't able to get a x86 one working) vm running node 18 and java 17, but no luck there.

If it dies without throwing any errors, there may be a native dependency version mismatch causing the crash, which is somewhat likely as adding the required dependencies resolves the issue.
In this case, using try...catch won't work, as this doesn't catch native crashes, just node errors.
Usually, an error popup should appear, telling you about missing dependencies.

If not and you want to check for the dependencies yourself, try searching for `vcruntime140.dll` on the target system.
This one is required by the addon and will be installed with the vc redistributable for vs 2015 (https://www.microsoft.com/en-gb/download/details.aspx?id=48145).

Or you could just ship the dll with your application, although I don't know how to do that but you wouldn't really use dlls as they are supposed to.

**Comment by tripower** [comment]
ok
thank you for the effort

**Comment by tripower** [comment]
guten Morgen

nochmals kurz zum Thema
in deinem Rust bzw Cpp Code kannst auch nichts checken oder anfangen und
selbst einen Error werfen?

liebe Grüße Klaus

Markus ***@***.***> schrieb am Mi., 24. Mai 2023, 18:31:
