### ISSUE TITLE
Add Explicit Resource Management to proxy object

### ISSUE THREAD

**Issue by sla100** [MarkusJx/node-java-bridge#91]
**Is your feature request related to a problem? Please describe.**

It is important to release `proxy` object when no longer in use. Ex.
```js

const proxy = java.newProxy(...);
try {
  // operations ... 
} finally {
  proxy.reset();
}
```

Typescript 5.2 and Node 20 introduced a new approach known e.g. in Java as try-resource:
```js
using proxy = java.newProxy(...);
// operations ... 
proxy.reset();
```

**Describe the solution you'd like**

The implementation requires adding an `Symbol.dispose` alias for the `reset` method in the `proxy` object.

**Additional context**

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management

https://tc39.es/proposal-explicit-resource-management/

**Comment by MarkusJx** [comment]
No, it's not *strictly necessary* to call `reset` on a [`JavaInterfaceProxy`](https://markusjx.github.io/node-java-bridge/interfaces/JavaInterfaceProxy.html). The inner proxy instance is already automatically destroyed once the garbage collector cleans up the `JavaInterfaceProxy` instance. Calling `reset` on the instance only speeds up the process as the garbage collector only runs in intervals. This is important if you want your application to exit as fast as possible as any existing interface proxies will prevent your application from closing (although `process.exit()` will stop the application instantly).

This is kind of documented in the [notes of `newProxy`](https://markusjx.github.io/node-java-bridge/functions/newProxy.html#md:notes), but I see where the confusion is coming from. I'll try to clarify this behavior in the docs (in #92).

Closing this issue as this is already implemented and the current implementation doesn't require a new node.js version.
